'use strict';

// generated by chatGPT
const additionalInfoController = module.exports;

additionalInfoController.get = async function (req, res) {
	// You can customize the data being sent to the template
	const data = {
		title: 'Additional Information',
	};

	// Render the additional-info template without the 'templates/' prefix
	res.render('additional-info', data);
};

